{% set version = "2.3.3" %}

package:
  name: bob.extension
  version: {{ version }}

source:
  fn: bob.extension-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.extension/bob.extension-{{ version }}.zip
  md5: af5e4165995a5d0a8a098a6d22aa0713

build:
  entry_points:
    - bob_new_version.py = bob.extension.scripts:new_version
    - bob_dependecy_graph.py = bob.extension.scripts:dependency_graph
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  requires:
    - nose
    - boost
    - cmake
    - pkg-config
    - freetype
    - libblitz
    - numpy

  imports:
    - bob
    - bob.extension
    - bob.extension.scripts

  commands:
    - bob_new_version.py --help
    - bob_dependecy_graph.py --help
    - nosetests -sv bob.extension  # [not osx]
    - CFLAGS="${CFLAGS} -pthread" LDFLAGS="${LDFLAGS} -lpthread" DYLD_FALLBACK_LIBRARY_PATH=$PREFIX/lib nosetests -sv bob.extension  # [osx]

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Building of Python/C++ extensions for Bob

extra:
  recipe-maintainers:
    - 183amir
