{% set version = "2.3.1" %}

package:
  name: bob.extension
  version: {{ version }}

source:
  fn: bob.extension-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.extension/bob.extension-{{ version }}.zip
  md5: 7e6b39ec4a9a9aff575e9d64873cec11
  patches:
    - test.patch

build:
  entry_points:
    - bob_new_version.py = bob.extension.scripts:new_version
    - bob_dependecy_graph.py = bob.extension.scripts:dependency_graph
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  requires:
    - cmake

  commands:
    - cmake --version
    - cmake

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Building of Python/C++ extensions for Bob

extra:
  recipe-maintainers:
    - 183amir
