travis:
  secure:
    BINSTAR_TOKEN: eA8NK/3JAjZ4ULcjqNGvHSZficC8+rHdu6ueD/+HGjOmcgwkHkvkQcR2neyAavfZjOqNoIX0duDTi5ZZaJIaoR6yZ+A9Tompxwxv/Biq+7zSAOvcue+KjLgx52ZFcEQwk1JxQJmGPhjwXk7kovXpPyBIq/FyjiUfacB7EJbimHKLwkvt4kJaeZ2JVlZv6BOwzzhb5/5X8M9IaB9B/JA7fPqm2XeaLcnzpu1P/XT6Fg6pzwPFkJo9bwBxc5YOEzo923uyPaHnlT3Zv+4hPJ9RpCt70iBraLwsJ71m9CE9cMF8j2oBxaqVMfMUlcSF5jodJBZL7JZtssN9KHGcPYWG5wfpWXEALHlYsyNN/ixzULKtMZSaYbI3DEZ6ZdG9PHe6WSLXJ62ZdN33eQQwfD95+YcraYqNv7Iyqj42jKoS1zriz7EJvra5ovPYO6K4YLBIjQhN+z2bd6tivokwzTk/oYb43okHgTwNB8JbOOYKqskS3ZzeQFu5GEnsrF+jV+9XUgKoNjusuNvFMIhgs9Ky332VGI45HPrxzZL/Dqsf2GYFDFWLr4jx0dQPlOZAxmbvCvFYe0GFIuvfAAoVj7Q+5hHJjegNjJi1E7s5LP3lXwzrIj2+KWg2HUD1RdqfJM6iTnCq4tVcyECCYzNT+wwOqdFPE1oE4b4FW1+sPKmY7NY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
